[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dual_spls"
authors = [
  { name="Louca Malerba", email="louca.malerba@student-cs.fr" },
]
description = "Implémentation Python de Dual-sPLS basée sur Alsouki et al. (2023)"
readme = "README.md"
requires-python = ">=3.9"

# Ici, tu mets les bibliothèques nécessaires (regarde ton requirements.txt)
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scikit-learn",
    "scipy"
]

[project.urls]
"Homepage" = "https://github.com/malerbe/dual-spls"


# Cette section dit à setuptools : "Le code est dans src/"
[tool.setuptools.packages.find]
where = ["src"]
