import numpy as np



def split(X,
          X_bin_indices,
          calList):
    """Splits data into calibration and validation sets according to wich group belongs each observation.

    Divides the data X into a calibration and a validation set using the Kennard and Stone strategy for
    each group at a time and according to the number of calibration desired from each group.

    Args:
        X (np.array): a numeric matrix
        X_bin_indices (np.array): a vector of index specifying to which group belongs each observation.
                                Typically generated by get_bin_indices.get_bin_indices()
        calList (np.array): a vector specifying how many observations from each group should be selected as calibration
                          Typically generated by callist.get_calList()
    """

    # check args consistency
    assert len(X_bin_indices) == X.shape[0]


if __name__ == "__main__":
    from dual_spls.simulate import simulate
    from dual_spls.get_bin_indices import get_bin_indices
    from dual_spls.callist import get_calList
    ## Configuration:
    # Simulation configuration:
    coefs = [0, 1, 0, 1, 1, 0, 0, 1, 1] 
    n = 300
    p = [1000]
    nondes = [30]
    sigmaondes = [0.40]
    sigma_y = 0.05

    # Split configuration:
    split_mode = "random"

    # Dual-sPLS configuration
    norm = "pseudo-lasso"

    simulation_results = simulate(n=n, p=p, nondes=nondes , sigmaondes=sigmaondes, sigma_y=sigma_y, coefs=coefs)
    X, y = simulation_results["X"], simulation_results["y"]

    bin_indices = get_bin_indices(y, n_bins=10)
    calList = get_calList(bin_indices, pcal=50)

    split(X, X_bin_indices=bin_indices, calList=calList)